services:
  tic_tac:
    build: .
    image: tic_tac:latest
    ports:
      - "2052:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=https://tictac.ctas.us

#defines service named tic_tac, builds image from Dockerfile in current directory
#tag the built image as latest
# exposes ports to host
# maps host port 65 to container port 5173
# # host: container is format
